name: Docker Image CI - dev

on:
  push:
    branches: [ "dev" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
    
      - name: Build and push -slim
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            alexinabox/cursors-backend:dev
            ghcr.io/alexinabox/cursors-backend:dev

      - name: Build and push -alpine
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.alpine
          tags: |
            alexinabox/cursors-backend:dev-alpine
            ghcr.io/alexinabox/cursors-backend:dev-alpine